force-app/main/default/objects/APICallout__mdt/APICallout__mdt.object-meta.xml
<CustomObject>
    <label>APICallout</label>
    <pluralLabel>APICallouts</pluralLabel>
</CustomObject>

force-app/main/default/objects/APICallout__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Office__c/Post_Office__c.object-meta.xml
<CustomObject>
    <label>Post Office</label>
    <nameField>
        <label>Post Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Post Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Post_Office__c/fields/Branch_Type__c.field-meta.xml
<CustomField>
    <fullName>Branch_Type__c</fullName>
    <label>Branch Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Office__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <label>Circle</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Office__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Post_Office__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PincodeCallout.cls
public with sharing class PincodeCallout {


    public static List<Post_Office__c> getPostOffice(Integer pincode){

        List<Post_Office__c> pOffices = new List<Post_Office__c>();
        List<Pincode_Wrapper.PostOffice> pwo = new List<Pincode_Wrapper.PostOffice>();

        APICallout__mdt callout = [SELECT Id, Endpoint__c FROM APICallout__mdt
                                    WHERE DeveloperName = 'StopPincodes'];
        String endPoint = callout.Endpoint__c + pincode;

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endPoint);
        request.setMethod('GET');
        HttpResponse response = http.send(request);

        system.debug(response.getStatusCode());

        Pincode_Wrapper pWrapper = Pincode_Wrapper.parse(response.getBody())[0];

        if(pWrapper.Status == 'Success'){
            for(Pincode_Wrapper.PostOffice po :pWrapper.PostOffice){
                pwo.add(po);
            }
        } else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'No Records Found'));
        }

        if(!pwo.isEmpty()){
            for(Pincode_Wrapper.PostOffice x :pwo){
                Post_Office__c y = new Post_Office__c();
                y.Name = x.Name;
                y.Pincode__c = Integer.valueOf(x.Pincode);
                y.Block__c = x.Block;
                y.Branch_Type__c = x.BranchType;
                y.Circle__c	= x.Circle;
                y.Country__c = x.Country;
                y.Delivery_Status__c = x.DeliveryStatus;
                y.Description__c = String.valueOf(x.Description);
                y.District__c = x.District;
                y.Division__c = x.Division;
                y.Region__c = x.Region;
                y.State__c = x.State;
                pOffices.add(y);    
            }
        }

        insert pOffices;

        return pOffices;

    }

}